# Generated by Django 4.0 on 2022-01-18 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testgram', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(related_name='profile_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
