# Generated by Django 4.0 on 2022-01-18 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testgram', '0008_remove_profile_follow_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='profile_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
