# Generated by Django 4.0 on 2022-01-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testgram', '0009_profile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
